services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - airflow-net

  postgres:
    image: postgres:13
    dns:
      - 8.8.8.8
    networks:
      - airflow-net
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    dns:
      - 8.8.8.8
    networks:
      - airflow-net

  airflow-webserver:
    build: ./airflow
    restart: always
    env_file:
      - .env
    dns:
      - 8.8.8.8
    networks:
      - airflow-net
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./great_expectations:/opt/airflow/great_expectations
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: ./airflow
    restart: always
    env_file:
      - .env
    dns:
      - 8.8.8.8
    networks:
      - airflow-net
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./great_expectations:/opt/airflow/great_expectations
    command: scheduler

  airflow-worker:
    build: ./airflow
    restart: always
    env_file:
      - .env
    dns:
      - 8.8.8.8
    networks:
      - airflow-net
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./great_expectations:/opt/airflow/great_expectations
    command: celery worker

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ssm
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - ./.localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init.sh
      - ./scripts/create_parameter_store.py:/etc/localstack/init/ready.d/10_create_parameter_store.py
    networks:
      - airflow-net

volumes:
  postgres-db-volume:
  minio_data:

networks:
  airflow-net:
    external: true